version: "3"

networks: 
  ame:
    driver: bridge

volumes: 
  mongo_data:
  node_modules:
  ame_dist:

services:
  mongo:
    build:
      context: ./mongo
    environment: 
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ame2020
      MONGO_INITDB_DATABASE: admin
    ports:
      - 127.0.0.1:27087:27087
    volumes: 
      - mongo_data:/data/db
      - ./mongo/createUser.sh:/docker-entrypoint-initdb.d/createUser.sh
      - ./mongo/initData.sh:/docker-entrypoint-initdb.d/initData.sh
    restart: always
    networks: 
      - ame

  nginx:
    build:
      context: ./nginx
    ports:
      - 127.0.0.1:8081:8081
    volumes:
      - ame_dist:/data/ame-dist
      - ./nginx/conf.d:/etc/nginx/conf.d
    restart: always
    networks:
      - ame

  nodejs:
    build:
      context: .
    ports:
      - 127.0.0.1:7001:7001
    volumes:
      - ame_dist:/data/ame-dist
      # - ./ame-server:/app/ame-server
      # - node_modules:/app/node_modules
    restart: always
    depends_on: 
      - mongo
      - nginx
    networks:
      - ame

  creator:
    build:
      context: ./ame-creator
    ports:
      - 127.0.0.1:8080:8080
    # volumes:
      # - ./ame-server:/app/ame-server
      # - node_modules:/app/node_modules
    restart: always
    depends_on: 
      - nodejs
    networks:
      - ame
